create table if not exists public.order_audit_log (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete restrict,
  from_status text,
  to_status text not null check (to_status in ('recibido','preparando','listo','completado','cancelado')),
  actor_user_id uuid,
  actor_role text not null default 'system' check (actor_role in ('system','kitchen','manager','admin','bot')),
  source text not null default 'database',
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.order_audit_log enable row level security;

create table if not exists public.order_rate_limits (
  key_hash text not null,
  window_start timestamptz not null,
  request_count integer not null default 0 check (request_count >= 0),
  updated_at timestamptz not null default now(),
  primary key (key_hash, window_start)
);

alter table public.order_rate_limits enable row level security;

create or replace function public.prevent_order_audit_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'order audit log is append-only';
end;
$$;

drop trigger if exists order_audit_log_immutable on public.order_audit_log;
create trigger order_audit_log_immutable
before update or delete on public.order_audit_log
for each row execute function public.prevent_order_audit_mutation();

create or replace function public.log_order_creation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.order_audit_log(order_id, from_status, to_status, actor_role, source)
  values (new.id, null, new.estado, 'system', 'order_created');
  return new;
end;
$$;

drop trigger if exists orders_log_creation on public.orders;
create trigger orders_log_creation
after insert on public.orders
for each row execute function public.log_order_creation();

create or replace function public.consume_order_rate_limit(
  p_key_hash text,
  p_limit integer default 12,
  p_window_seconds integer default 60
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_window_start timestamptz;
  v_count integer;
begin
  if p_key_hash is null or length(p_key_hash) < 32 then
    raise exception 'invalid rate-limit key';
  end if;
  if p_limit < 1 or p_limit > 1000 then
    raise exception 'invalid rate-limit limit';
  end if;
  if p_window_seconds < 10 or p_window_seconds > 3600 then
    raise exception 'invalid rate-limit window';
  end if;

  v_window_start := to_timestamp(
    floor(extract(epoch from clock_timestamp()) / p_window_seconds) * p_window_seconds
  );

  insert into public.order_rate_limits(key_hash, window_start, request_count, updated_at)
  values (p_key_hash, v_window_start, 1, now())
  on conflict (key_hash, window_start)
  do update set
    request_count = public.order_rate_limits.request_count + 1,
    updated_at = now()
  returning request_count into v_count;

  if random() < 0.02 then
    delete from public.order_rate_limits
    where window_start < now() - interval '2 hours';
  end if;

  return v_count <= p_limit;
end;
$$;

create or replace function public.staff_update_order_status(
  p_order_id text,
  p_new_status text,
  p_actor_user_id uuid,
  p_actor_role text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old_status text;
  v_updated_at timestamptz;
begin
  if p_actor_user_id is null then
    raise exception 'actor required';
  end if;
  if p_actor_role not in ('kitchen','manager','admin') then
    raise exception 'unauthorized role';
  end if;
  if p_new_status not in ('recibido','preparando','listo','completado','cancelado') then
    raise exception 'invalid status';
  end if;

  select estado into v_old_status
  from public.orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'order not found';
  end if;

  if v_old_status = p_new_status then
    select updated_at into v_updated_at from public.orders where id = p_order_id;
    return jsonb_build_object('id', p_order_id, 'estado', p_new_status, 'updated_at', v_updated_at, 'changed', false);
  end if;

  if not (
    (v_old_status = 'recibido' and p_new_status in ('preparando','cancelado')) or
    (v_old_status = 'preparando' and p_new_status in ('listo','cancelado')) or
    (v_old_status = 'listo' and p_new_status in ('completado','cancelado'))
  ) then
    raise exception 'invalid status transition from % to %', v_old_status, p_new_status;
  end if;

  update public.orders
  set estado = p_new_status,
      updated_at = now()
  where id = p_order_id
  returning updated_at into v_updated_at;

  insert into public.order_audit_log(order_id, from_status, to_status, actor_user_id, actor_role, source)
  values (p_order_id, v_old_status, p_new_status, p_actor_user_id, p_actor_role, 'staff_api');

  return jsonb_build_object('id', p_order_id, 'estado', p_new_status, 'updated_at', v_updated_at, 'changed', true);
end;
$$;

revoke all on function public.consume_order_rate_limit(text, integer, integer) from public, anon, authenticated;
revoke all on function public.staff_update_order_status(text, text, uuid, text) from public, anon, authenticated;
grant execute on function public.consume_order_rate_limit(text, integer, integer) to service_role;
grant execute on function public.staff_update_order_status(text, text, uuid, text) to service_role;
